/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardObjectTypeIndexRouteImport } from './routes/dashboard/object-type/index'
import { Route as DashboardItemIndexRouteImport } from './routes/dashboard/item/index'
import { Route as DashboardObjectTypeCreateRouteImport } from './routes/dashboard/object-type/create'
import { Route as DashboardItemCreateRouteImport } from './routes/dashboard/item/create'
import { Route as DashboardObjectTypeIdIndexRouteImport } from './routes/dashboard/object-type/$id/index'
import { Route as DashboardItemIdIndexRouteImport } from './routes/dashboard/item/$id/index'
import { Route as DashboardObjectTypeIdEditRouteImport } from './routes/dashboard/object-type/$id/edit'
import { Route as DashboardItemIdEditRouteImport } from './routes/dashboard/item/$id/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardObjectTypeIndexRoute =
  DashboardObjectTypeIndexRouteImport.update({
    id: '/object-type/',
    path: '/object-type/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemIndexRoute = DashboardItemIndexRouteImport.update({
  id: '/item/',
  path: '/item/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardObjectTypeCreateRoute =
  DashboardObjectTypeCreateRouteImport.update({
    id: '/object-type/create',
    path: '/object-type/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemCreateRoute = DashboardItemCreateRouteImport.update({
  id: '/item/create',
  path: '/item/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardObjectTypeIdIndexRoute =
  DashboardObjectTypeIdIndexRouteImport.update({
    id: '/object-type/$id/',
    path: '/object-type/$id/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemIdIndexRoute = DashboardItemIdIndexRouteImport.update({
  id: '/item/$id/',
  path: '/item/$id/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardObjectTypeIdEditRoute =
  DashboardObjectTypeIdEditRouteImport.update({
    id: '/object-type/$id/edit',
    path: '/object-type/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardItemIdEditRoute = DashboardItemIdEditRouteImport.update({
  id: '/item/$id/edit',
  path: '/item/$id/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/item/create': typeof DashboardItemCreateRoute
  '/dashboard/object-type/create': typeof DashboardObjectTypeCreateRoute
  '/dashboard/item': typeof DashboardItemIndexRoute
  '/dashboard/object-type': typeof DashboardObjectTypeIndexRoute
  '/dashboard/item/$id/edit': typeof DashboardItemIdEditRoute
  '/dashboard/object-type/$id/edit': typeof DashboardObjectTypeIdEditRoute
  '/dashboard/item/$id': typeof DashboardItemIdIndexRoute
  '/dashboard/object-type/$id': typeof DashboardObjectTypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/item/create': typeof DashboardItemCreateRoute
  '/dashboard/object-type/create': typeof DashboardObjectTypeCreateRoute
  '/dashboard/item': typeof DashboardItemIndexRoute
  '/dashboard/object-type': typeof DashboardObjectTypeIndexRoute
  '/dashboard/item/$id/edit': typeof DashboardItemIdEditRoute
  '/dashboard/object-type/$id/edit': typeof DashboardObjectTypeIdEditRoute
  '/dashboard/item/$id': typeof DashboardItemIdIndexRoute
  '/dashboard/object-type/$id': typeof DashboardObjectTypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/item/create': typeof DashboardItemCreateRoute
  '/dashboard/object-type/create': typeof DashboardObjectTypeCreateRoute
  '/dashboard/item/': typeof DashboardItemIndexRoute
  '/dashboard/object-type/': typeof DashboardObjectTypeIndexRoute
  '/dashboard/item/$id/edit': typeof DashboardItemIdEditRoute
  '/dashboard/object-type/$id/edit': typeof DashboardObjectTypeIdEditRoute
  '/dashboard/item/$id/': typeof DashboardItemIdIndexRoute
  '/dashboard/object-type/$id/': typeof DashboardObjectTypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/item/create'
    | '/dashboard/object-type/create'
    | '/dashboard/item'
    | '/dashboard/object-type'
    | '/dashboard/item/$id/edit'
    | '/dashboard/object-type/$id/edit'
    | '/dashboard/item/$id'
    | '/dashboard/object-type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/item/create'
    | '/dashboard/object-type/create'
    | '/dashboard/item'
    | '/dashboard/object-type'
    | '/dashboard/item/$id/edit'
    | '/dashboard/object-type/$id/edit'
    | '/dashboard/item/$id'
    | '/dashboard/object-type/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/item/create'
    | '/dashboard/object-type/create'
    | '/dashboard/item/'
    | '/dashboard/object-type/'
    | '/dashboard/item/$id/edit'
    | '/dashboard/object-type/$id/edit'
    | '/dashboard/item/$id/'
    | '/dashboard/object-type/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/object-type/': {
      id: '/dashboard/object-type/'
      path: '/object-type'
      fullPath: '/dashboard/object-type'
      preLoaderRoute: typeof DashboardObjectTypeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/item/': {
      id: '/dashboard/item/'
      path: '/item'
      fullPath: '/dashboard/item'
      preLoaderRoute: typeof DashboardItemIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/object-type/create': {
      id: '/dashboard/object-type/create'
      path: '/object-type/create'
      fullPath: '/dashboard/object-type/create'
      preLoaderRoute: typeof DashboardObjectTypeCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/item/create': {
      id: '/dashboard/item/create'
      path: '/item/create'
      fullPath: '/dashboard/item/create'
      preLoaderRoute: typeof DashboardItemCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/object-type/$id/': {
      id: '/dashboard/object-type/$id/'
      path: '/object-type/$id'
      fullPath: '/dashboard/object-type/$id'
      preLoaderRoute: typeof DashboardObjectTypeIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/item/$id/': {
      id: '/dashboard/item/$id/'
      path: '/item/$id'
      fullPath: '/dashboard/item/$id'
      preLoaderRoute: typeof DashboardItemIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/object-type/$id/edit': {
      id: '/dashboard/object-type/$id/edit'
      path: '/object-type/$id/edit'
      fullPath: '/dashboard/object-type/$id/edit'
      preLoaderRoute: typeof DashboardObjectTypeIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/item/$id/edit': {
      id: '/dashboard/item/$id/edit'
      path: '/item/$id/edit'
      fullPath: '/dashboard/item/$id/edit'
      preLoaderRoute: typeof DashboardItemIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardItemCreateRoute: typeof DashboardItemCreateRoute
  DashboardObjectTypeCreateRoute: typeof DashboardObjectTypeCreateRoute
  DashboardItemIndexRoute: typeof DashboardItemIndexRoute
  DashboardObjectTypeIndexRoute: typeof DashboardObjectTypeIndexRoute
  DashboardItemIdEditRoute: typeof DashboardItemIdEditRoute
  DashboardObjectTypeIdEditRoute: typeof DashboardObjectTypeIdEditRoute
  DashboardItemIdIndexRoute: typeof DashboardItemIdIndexRoute
  DashboardObjectTypeIdIndexRoute: typeof DashboardObjectTypeIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardItemCreateRoute: DashboardItemCreateRoute,
  DashboardObjectTypeCreateRoute: DashboardObjectTypeCreateRoute,
  DashboardItemIndexRoute: DashboardItemIndexRoute,
  DashboardObjectTypeIndexRoute: DashboardObjectTypeIndexRoute,
  DashboardItemIdEditRoute: DashboardItemIdEditRoute,
  DashboardObjectTypeIdEditRoute: DashboardObjectTypeIdEditRoute,
  DashboardItemIdIndexRoute: DashboardItemIdIndexRoute,
  DashboardObjectTypeIdIndexRoute: DashboardObjectTypeIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
